### ISSUE TITLE
Incorrect path parsing

### ISSUE THREAD

**Issue by diomidov** [diagrams/diagrams-input#17]
I have the following path:
```svg
<!-- https://fontawesome.com/icons/flag?style=solid CC-BY -->
<path fill="Indigo" d="M349.565 98.783C295.978 98.783 251.721 64 184.348 64c-24.955 0-47.309 4.384-68.045 12.013a55.947 55.947 0 0 0 3.586-23.562C118.117 24.015 94.806 1.206 66.338.048 34.345-1.254 8 24.296 8 56c0 19.026 9.497 35.825 24 45.945V488c0 13.255 10.745 24 24 24h16c13.255 0 24-10.745 24-24v-94.4c28.311-12.064 63.582-22.122 114.435-22.122 53.588 0 97.844 34.783 165.217 34.783 48.169 0 86.667-16.294 122.505-40.858C506.84 359.452 512 349.571 512 339.045v-243.1c0-23.393-24.269-38.87-45.485-29.016-34.338 15.948-76.454 31.854-116.95 31.854z"></path>
```

Firefox renders it like this:
![image](https://user-images.githubusercontent.com/22151995/231363851-10d583ea-1a18-4b5c-812f-cd43e2d98dcf.png)

But with this library I get this:
![image](https://user-images.githubusercontent.com/22151995/231364019-93139bdf-b434-4bdc-9e00-c47760934faf.png)

It looks like it stops at "C118.117 24.015 94.806 1.206 ***66.338.048***". According to the [spec](https://svgwg.org/svg2-draft/paths.html#PathDataBNF), this is actually valid and should be parsed as `66.338 0.048`! :open_mouth:

> Similarly, for the string "M 0.6.5", the first coordinate of the "moveto" consumes the characters "0.6" and stops upon encountering the second decimal point because the production of a "coordinate" only allows one decimal point. The result is that the first coordinate will be "0.6" and the second coordinate will be ".5".

**Comment by diomidov** [comment]
It appears there's also an issue with the `a` command. It looks like it doesn't update the current point correctly.

![image](https://user-images.githubusercontent.com/22151995/231372311-6914b882-a949-4597-940e-88a2ef163db9.png)

```
-- working (q)
m 349.565 98.783 c -53.587 0 -97.844 -34.783 -165.217 -34.783 c -24.955 0 -47.309 4.384 -68.045 12.013 q 4.697 -11.013 3.586 -23.562 c -1.772 -28.436 -25.083 -51.245 -53.551 -52.403 c -31.993 -1.302 -58.338 24.248 -58.338 55.952 c 0 19.026 9.497 35.825 24 45.945 v 386.055 c 0 13.255 10.745 24 24 24 h 16 c 13.255 0 24 -10.745 24 -24 v -94.4 c 28.311 -12.064 63.582 -22.122 114.435 -22.122 c 53.588 0 97.844 34.783 165.217 34.783 c 48.169 0 86.667 -16.294 122.505 -40.858 c 8.683 -5.951 13.843 -15.832 13.843 -26.358 v -243.1 c 0 -23.393 -24.269 -38.87 -45.485 -29.016 c -34.338 15.948 -76.454 31.854 -116.95 31.854 z
-- broken (a)
m 349.565 98.783 c -53.587 0 -97.844 -34.783 -165.217 -34.783 c -24.955 0 -47.309 4.384 -68.045 12.013 a 55.947 55.947 90 0 0 3.586 -23.562 c -1.772 -28.436 -25.083 -51.245 -53.551 -52.403 c -31.993 -1.302 -58.338 24.248 -58.338 55.952 c 0 19.026 9.497 35.825 24 45.945 v 386.055 c 0 13.255 10.745 24 24 24 h 16 c 13.255 0 24 -10.745 24 -24 v -94.4 c 28.311 -12.064 63.582 -22.122 114.435 -22.122 c 53.588 0 97.844 34.783 165.217 34.783 c 48.169 0 86.667 -16.294 122.505 -40.858 c 8.683 -5.951 13.843 -15.832 13.843 -26.358 v -243.1 c 0 -23.393 -24.269 -38.87 -45.485 -29.016 c -34.338 15.948 -76.454 31.854 -116.95 31.854 z
```

**Comment by tkvogt** [comment]
It seems like the double parser from Attoparsec.Text has to be reimplemented for the first issue. If you don't fix I will do this over the weekend.

**Comment by byorgey** [comment]
I'll upload a new version with this fix soon!
